export const LIST_REQUEST = "JOBS/LIST_REQUEST";
export const LIST_SUCCESS = "JOBS/LIST_SUCCESS";
export const LIST_FAILURE = "JOBS/LIST_FAILURE";

export const SAVE_REQUEST = "JOBS/SAVE_REQUEST";
export const SAVE_SUCCESS = "JOBS/SAVE_SUCCESS";
export const SAVE_FAILURE = "JOBS/SAVE_FAILURE";

export const FETCH_JOB_REQUEST = "JOBS/FETCH_JOB_REQUEST";
export const FETCH_JOB_SUCCESS = "JOBS/FETCH_JOB_SUCCESS";
export const FETCH_JOB_FAILURE = "JOBS/FETCH_JOB_FAILURE";

export const CANCEL_REQUEST = "JOBS/CANCEL_REQUEST";
export const CANCEL_SUCCESS = "JOBS/CANCEL_SUCCESS";
export const CANCEL_FAILURE = "JOBS/CANCEL_FAILURE";

export const FETCH_ALL_FOR_COPY_REQUEST = "JOBS/FETCH_ALL_FOR_COPY_REQUEST";
export const FETCH_ALL_FOR_COPY_SUCCESS = "JOBS/FETCH_ALL_FOR_COPY_SUCCESS";
export const FETCH_ALL_FOR_COPY_FAILURE = "JOBS/FETCH_ALL_FOR_COPY_FAILURE";
