export const UPDATE_PROFILE_REQUEST = "MYPAGE/UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "MYPAGE/UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "MYPAGE/UPDATE_PROFILE_FAIL";

export const UPDATE_AVATAR_REQUEST = "MYPAGE/UPDATE_AVATAR_REQUEST";
export const UPDATE_AVATAR_SUCCESS = "MYPAGE/UPDATE_AVATAR_SUCCESS";
export const UPDATE_AVATAR_FAIL = "MYPAGE/UPDATE_AVATAR_FAIL";

export const UPDATE_PASSWORD_REQUEST = "MYPAGE/UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "MYPAGE/UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAILURE = "MYPAGE/UPDATE_PASSWORD_FAILURE";
