export const CANDIDATES_FOR_JOB = "DASHBOARD/CANDIDATES_FOR_JOB";
export const CANDIDATES_FOR_JOB_REQUEST = "DASHBOARD/CANDIDATES_FOR_JOB_REQUEST";
export const CANDIDATES_FOR_JOB_SUCCESS = "DASHBOARD/CANDIDATES_FOR_JOB_SUCCESS";
export const CANDIDATES_FOR_JOB_FAILURE = "DASHBOARD/CANDIDATES_FOR_JOB_FAILURE";
export const CANDIDATE_PROFILE_REQUEST = "DASHBOARD/CANDIDATE_PROFILE_REQUEST";
export const CANDIDATE_PROFILE_SUCCESS = "DASHBOARD/CANDIDATE_PROFILE_SUCCESS";
export const CANDIDATE_PROFILE_FAILURE = "DASHBOARD/CANDIDATE_PROFILE_FAILURE";
export const CANDIDATES_BY_TYPE_REQUEST = "DASHBOARD/CANDIDATES_BY_TYPE_REQUEST";
export const CANDIDATES_BY_TYPE_SUCCESS = "DASHBOARD/CANDIDATES_BY_TYPE_SUCCESS";
export const CANDIDATES_BY_TYPE_FAILURE = "DASHBOARD/CANDIDATES_BY_TYPE_FAILURE";

export const CANDIDATES_FOR_NOTIFICATIONS_REQUEST = "DASHBOARD/CANDIDATES_FOR_NOTIFICATIONS_REQUEST";
export const CANDIDATES_FOR_NOTIFICATIONS_SUCCESS = "DASHBOARD/CANDIDATES_FOR_NOTIFICATIONS_SUCCESS";
export const CANDIDATES_FOR_NOTIFICATIONS_FAILURE = "DASHBOARD/CANDIDATES_FOR_NOTIFICATIONS_FAILURE";

export const CREATE_REVIEW_REQUEST = "DASHBOARD/CREATE_REVIEW_REQUEST";
export const CREATE_REVIEW_SUCCESS = "DASHBOARD/CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_FAILURE = "DASHBOARD/CREATE_REVIEW_FAILURE";
