export const FETCH_TIMEREPORT_REQUEST = "JOBS/FETCH_TIMEREPORT_REQUEST";
export const FETCH_TIMEREPORT_SUCCESS = "JOBS/FETCH_TIMEREPORT_SUCCESS";
export const FETCH_TIMEREPORT_FAILURE = "JOBS/FETCH_TIMEREPORT_FAILURE";

export const UPDATE_SHIFT_REQUEST = "JOBS/UPDATE_SHIFT_REQUEST";
export const UPDATE_SHIFT_SUCCESS = "JOBS/UPDATE_SHIFT_SUCCESS";
export const UPDATE_SHIFT_FAILURE = "JOBS/UPDATE_SHIFT_FAILURE";
