export const SIGNUP_REQUEST = "AUTH/SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "AUTH/SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "AUTH/SIGNUP_FAIL";

export const LOGIN_REQUEST = 'AUTH/LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'AUTH/LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'AUTH/LOGIN_FAILURE';

export const VERIFY_LOGIN_REQUEST = 'AUTH/VERIFY_LOGIN_REQUEST';
export const VERIFY_LOGIN_COMPLETE = 'AUTH/VERIFY_LOGIN_COMPLETE';

export const LOGOUT_REQUEST = 'AUTH/LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'AUTH/LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'AUTH/LOGOUT_FAILURE';

export const FORGOT_PASSWORD_REQUEST = 'AUTH/FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'AUTH/FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'AUTH/FORGOT_PASSWORD_FAILURE';

export const RECEIVE_UPDATED_USER = 'AUTH/RECEIVE_UPDATED_USER';
export const UPDATE_USER_PROFILE_PIC = 'AUTH/UPDATE_USER_PROFILE_PIC';
