export const NOTIFICATIONS_REQUEST = "NOTIFICATIONS/NOTIFICATIONS_REQUEST";
export const NOTIFICATIONS_SUCCESS = "NOTIFICATIONS/NOTIFICATIONS_SUCCESS";
export const NOTIFICATIONS_FAILURE = "NOTIFICATIONS/NOTIFICATIONS_FAILURE";
export const NOTIFICATIONS_DELETE_REQUEST = "NOTIFICATIONS/NOTIFICATIONS_DELETE_REQUEST";
export const NOTIFICATIONS_DELETE_SUCCESS = "NOTIFICATIONS/NOTIFICATIONS_DELETE_SUCCESS";
export const NOTIFICATIONS_DELETE_FAILURE = "NOTIFICATIONS/NOTIFICATIONS_DELETE_FAILURE";
export const NOTIFICATIONS_COUNT_RECEIVED = "NOTIFICATIONS/NOTIFICATIONS_COUNT_RECEIVED";
export const NEW_NOTIFICATION = "NOTIFICATIONS/NEW_NOTIFICATION";
